
server.host: 127.0.0.1
server.port: 10000
routes:
      # 路由的ID，没有固定规则，但要求唯一，建议配合服务名
  - id: test
      # 匹配后提供服务的路由地址
    uri:
      # 不包含协议头
      - 127.0.0.1:9090
      # 断言，路径相匹配的进行路由
    predicates:
      - Path=/
